name: Bandit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install bandit
        run: pip install bandit
      - name: Run bandit
        run: python3 -m bandit .