name: coverage-code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup poetry
        run : |
          pipx install poetry
          pipx upgrade poetry
