name: poetry

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v2

      - name: Set up Python  ${{ matrix.python-version }}
        uses: actions/setup-python@v4

      - name: Setup poetry
        run : |
          pipx install poetry
          pipx upgrade poetry
          poetry run python -V
