name: Pypi

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v2

      - name: Set up Python  ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Setup Pypi
        run : |
          pip install pip-install-test
          pip install pip-run