name: pytest

on: [push]

jobs :
  lint :
    runs-on : ubuntu-lastest
    steps :
      - name : Checkout
        uses: actions/checkout@v2

      - name: Set up Python  ${{ matrix.python-version }}
        uses: actions/setup-python@v4

      - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install -e .

      - name: Run unit tests
          run: python -m pytest example/migrations/test.py