name: pytest

on: [push]

jobs :
  lint :
    runs-on : ubuntu-lastest
    steps :
      - uses: actions/checkout@v2
      - uses: pyupio/safety@2.3.1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}